# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(640, 480)
		self.verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.verticalLayoutWidget.sizePolicy().hasHeightForWidth())
		self.verticalLayoutWidget.setSizePolicy(sizePolicy)
		self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
		self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.menuBar = QtWidgets.QMenuBar(self.verticalLayoutWidget)
		self.menuBar.setNativeMenuBar(True)
		self.menuBar.setObjectName("menuBar")
		self.menuFile = QtWidgets.QMenu(self.menuBar)
		self.menuFile.setObjectName("menuFile")
		self.menuExport_Report = QtWidgets.QMenu(self.menuFile)
		self.menuExport_Report.setObjectName("menuExport_Report")
		self.menuEdit = QtWidgets.QMenu(self.menuBar)
		self.menuEdit.setObjectName("menuEdit")
		self.menuTools = QtWidgets.QMenu(self.menuBar)
		self.menuTools.setObjectName("menuTools")
		self.menuHelp = QtWidgets.QMenu(self.menuBar)
		self.menuHelp.setObjectName("menuHelp")
		self.verticalLayout.addWidget(self.menuBar)
		self.profileTools = QtWidgets.QHBoxLayout()
		self.profileTools.setContentsMargins(2, 2, 2, 2)
		self.profileTools.setSpacing(6)
		self.profileTools.setObjectName("profileTools")
		self.profileLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.profileLabel.setObjectName("profileLabel")
		self.profileTools.addWidget(self.profileLabel)
		self.profileName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.profileName.sizePolicy().hasHeightForWidth())
		self.profileName.setSizePolicy(sizePolicy)
		self.profileName.setObjectName("profileName")
		self.profileTools.addWidget(self.profileName)
		self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
		self.label.setObjectName("label")
		self.profileTools.addWidget(self.label)
		self.contextBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
		self.contextBox.setObjectName("contextBox")
		self.profileTools.addWidget(self.contextBox)
		self.contextWidgetContainer = QtWidgets.QHBoxLayout()
		self.contextWidgetContainer.setContentsMargins(2, 2, 2, 2)
		self.contextWidgetContainer.setSpacing(2)
		self.contextWidgetContainer.setObjectName("contextWidgetContainer")
		self.profileTools.addLayout(self.contextWidgetContainer)
		spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.profileTools.addItem(spacerItem)
		self.verticalLayout.addLayout(self.profileTools)
		self.workspaceSplitter = QtWidgets.QSplitter(self.verticalLayoutWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.workspaceSplitter.sizePolicy().hasHeightForWidth())
		self.workspaceSplitter.setSizePolicy(sizePolicy)
		self.workspaceSplitter.setOrientation(QtCore.Qt.Horizontal)
		self.workspaceSplitter.setChildrenCollapsible(False)
		self.workspaceSplitter.setObjectName("workspaceSplitter")
		self.reportToolsWidget = QtWidgets.QWidget(self.workspaceSplitter)
		self.reportToolsWidget.setObjectName("reportToolsWidget")
		self.reportTools = QtWidgets.QVBoxLayout(self.reportToolsWidget)
		self.reportTools.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
		self.reportTools.setContentsMargins(2, 2, 2, 2)
		self.reportTools.setSpacing(0)
		self.reportTools.setObjectName("reportTools")
		self.sectionList = QtWidgets.QListWidget(self.reportToolsWidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.sectionList.sizePolicy().hasHeightForWidth())
		self.sectionList.setSizePolicy(sizePolicy)
		self.sectionList.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.sectionList.setTabKeyNavigation(True)
		self.sectionList.setDragEnabled(True)
		self.sectionList.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
		self.sectionList.setDefaultDropAction(QtCore.Qt.MoveAction)
		self.sectionList.setObjectName("sectionList")
		self.reportTools.addWidget(self.sectionList)
		self.sectionTools = QtWidgets.QHBoxLayout()
		self.sectionTools.setContentsMargins(2, 2, 2, 2)
		self.sectionTools.setSpacing(0)
		self.sectionTools.setObjectName("sectionTools")
		self.saveProfile = QtWidgets.QToolButton(self.reportToolsWidget)
		self.saveProfile.setEnabled(True)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.saveProfile.sizePolicy().hasHeightForWidth())
		self.saveProfile.setSizePolicy(sizePolicy)
		self.saveProfile.setObjectName("saveProfile")
		self.sectionTools.addWidget(self.saveProfile)
		self.openProfile = QtWidgets.QToolButton(self.reportToolsWidget)
		self.openProfile.setText("")
		self.openProfile.setObjectName("openProfile")
		self.sectionTools.addWidget(self.openProfile)
		spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.sectionTools.addItem(spacerItem1)
		self.moveUp = QtWidgets.QToolButton(self.reportToolsWidget)
		self.moveUp.setEnabled(False)
		self.moveUp.setObjectName("moveUp")
		self.sectionTools.addWidget(self.moveUp)
		self.moveDown = QtWidgets.QToolButton(self.reportToolsWidget)
		self.moveDown.setEnabled(False)
		self.moveDown.setObjectName("moveDown")
		self.sectionTools.addWidget(self.moveDown)
		self.removeSection = QtWidgets.QToolButton(self.reportToolsWidget)
		self.removeSection.setEnabled(False)
		self.removeSection.setObjectName("removeSection")
		self.sectionTools.addWidget(self.removeSection)
		self.addSection = QtWidgets.QToolButton(self.reportToolsWidget)
		self.addSection.setEnabled(True)
		self.addSection.setObjectName("addSection")
		self.sectionTools.addWidget(self.addSection)
		self.reportTools.addLayout(self.sectionTools)
		self.sectionSeperator = QtWidgets.QFrame(self.reportToolsWidget)
		self.sectionSeperator.setFrameShape(QtWidgets.QFrame.HLine)
		self.sectionSeperator.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.sectionSeperator.setObjectName("sectionSeperator")
		self.reportTools.addWidget(self.sectionSeperator)
		self.reportActions = QtWidgets.QHBoxLayout()
		self.reportActions.setContentsMargins(2, 2, 2, 2)
		self.reportActions.setSpacing(0)
		self.reportActions.setObjectName("reportActions")
		self.generateReport = QtWidgets.QPushButton(self.reportToolsWidget)
		self.generateReport.setEnabled(False)
		self.generateReport.setObjectName("generateReport")
		self.reportActions.addWidget(self.generateReport)
		spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.reportActions.addItem(spacerItem2)
		self.exportReport = QtWidgets.QToolButton(self.reportToolsWidget)
		self.exportReport.setEnabled(False)
		self.exportReport.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
		self.exportReport.setObjectName("exportReport")
		self.reportActions.addWidget(self.exportReport)
		self.reportTools.addLayout(self.reportActions)
		self.pluginToolsWidget = QtWidgets.QWidget(self.workspaceSplitter)
		self.pluginToolsWidget.setObjectName("pluginToolsWidget")
		self.pluginTools = QtWidgets.QVBoxLayout(self.pluginToolsWidget)
		self.pluginTools.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
		self.pluginTools.setContentsMargins(2, 2, 2, 2)
		self.pluginTools.setSpacing(0)
		self.pluginTools.setObjectName("pluginTools")
		self.pluginInfo = QtWidgets.QHBoxLayout()
		self.pluginInfo.setContentsMargins(2, 2, 2, 2)
		self.pluginInfo.setSpacing(6)
		self.pluginInfo.setObjectName("pluginInfo")
		self.sectionTitle = QtWidgets.QLineEdit(self.pluginToolsWidget)
		self.sectionTitle.setEnabled(True)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.sectionTitle.sizePolicy().hasHeightForWidth())
		self.sectionTitle.setSizePolicy(sizePolicy)
		self.sectionTitle.setFrame(True)
		self.sectionTitle.setObjectName("sectionTitle")
		self.pluginInfo.addWidget(self.sectionTitle)
		self.pluginTypeLabel = QtWidgets.QLabel(self.pluginToolsWidget)
		self.pluginTypeLabel.setObjectName("pluginTypeLabel")
		self.pluginInfo.addWidget(self.pluginTypeLabel)
		self.pluginButton = QtWidgets.QPushButton(self.pluginToolsWidget)
		font = QtGui.QFont()
		font.setBold(False)
		font.setItalic(True)
		font.setWeight(50)
		self.pluginButton.setFont(font)
		self.pluginButton.setAutoFillBackground(True)
		self.pluginButton.setFlat(False)
		self.pluginButton.setObjectName("pluginButton")
		self.pluginInfo.addWidget(self.pluginButton)
		self.pluginSettingsWidget = QtWidgets.QWidget(self.pluginToolsWidget)
		self.pluginSettingsWidget.setEnabled(False)
		self.pluginSettingsWidget.setObjectName("pluginSettingsWidget")
		self.pluginSettings = QtWidgets.QHBoxLayout(self.pluginSettingsWidget)
		self.pluginSettings.setContentsMargins(2, 2, 6, 2)
		self.pluginSettings.setSpacing(2)
		self.pluginSettings.setObjectName("pluginSettings")
		self.showTitle = QtWidgets.QCheckBox(self.pluginSettingsWidget)
		self.showTitle.setChecked(True)
		self.showTitle.setObjectName("showTitle")
		self.pluginSettings.addWidget(self.showTitle)
		self.pluginInfo.addWidget(self.pluginSettingsWidget)
		spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
		self.pluginInfo.addItem(spacerItem3)
		self.pluginTools.addLayout(self.pluginInfo)
		self.pluginOptions = QtWidgets.QScrollArea(self.pluginToolsWidget)
		self.pluginOptions.setEnabled(False)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pluginOptions.sizePolicy().hasHeightForWidth())
		self.pluginOptions.setSizePolicy(sizePolicy)
		self.pluginOptions.setWidgetResizable(True)
		self.pluginOptions.setObjectName("pluginOptions")
		self.pluginTools.addWidget(self.pluginOptions)
		self.pluginTools.setStretch(1, 1)
		self.verticalLayout.addWidget(self.workspaceSplitter)
		MainWindow.setCentralWidget(self.verticalLayoutWidget)
		self.statusBar = QtWidgets.QStatusBar(MainWindow)
		self.statusBar.setObjectName("statusBar")
		MainWindow.setStatusBar(self.statusBar)
		self.actionOpen = QtWidgets.QAction(MainWindow)
		self.actionOpen.setEnabled(False)
		self.actionOpen.setObjectName("actionOpen")
		self.actionSave_Report = QtWidgets.QAction(MainWindow)
		self.actionSave_Report.setEnabled(False)
		self.actionSave_Report.setObjectName("actionSave_Report")
		self.actionSave_Profile = QtWidgets.QAction(MainWindow)
		self.actionSave_Profile.setEnabled(True)
		self.actionSave_Profile.setObjectName("actionSave_Profile")
		self.action_docx = QtWidgets.QAction(MainWindow)
		self.action_docx.setEnabled(False)
		self.action_docx.setObjectName("action_docx")
		self.action_PDF = QtWidgets.QAction(MainWindow)
		self.action_PDF.setEnabled(False)
		self.action_PDF.setObjectName("action_PDF")
		self.action_odf = QtWidgets.QAction(MainWindow)
		self.action_odf.setEnabled(False)
		self.action_odf.setObjectName("action_odf")
		self.actionQuit = QtWidgets.QAction(MainWindow)
		self.actionQuit.setObjectName("actionQuit")
		self.actionAdd_Section = QtWidgets.QAction(MainWindow)
		self.actionAdd_Section.setEnabled(True)
		self.actionAdd_Section.setObjectName("actionAdd_Section")
		self.actionRemove_Section = QtWidgets.QAction(MainWindow)
		self.actionRemove_Section.setEnabled(False)
		self.actionRemove_Section.setObjectName("actionRemove_Section")
		self.actionMove_Section_Up = QtWidgets.QAction(MainWindow)
		self.actionMove_Section_Up.setEnabled(False)
		self.actionMove_Section_Up.setObjectName("actionMove_Section_Up")
		self.actionMove_Section_Down = QtWidgets.QAction(MainWindow)
		self.actionMove_Section_Down.setEnabled(False)
		self.actionMove_Section_Down.setObjectName("actionMove_Section_Down")
		self.actionImport_Package = QtWidgets.QAction(MainWindow)
		self.actionImport_Package.setEnabled(False)
		self.actionImport_Package.setObjectName("actionImport_Package")
		self.actionRemove_Package = QtWidgets.QAction(MainWindow)
		self.actionRemove_Package.setEnabled(False)
		self.actionRemove_Package.setObjectName("actionRemove_Package")
		self.actionGenerate_Report = QtWidgets.QAction(MainWindow)
		self.actionGenerate_Report.setEnabled(False)
		self.actionGenerate_Report.setObjectName("actionGenerate_Report")
		self.actionARCTool_Wiki = QtWidgets.QAction(MainWindow)
		self.actionARCTool_Wiki.setEnabled(False)
		self.actionARCTool_Wiki.setObjectName("actionARCTool_Wiki")
		self.actionAbout = QtWidgets.QAction(MainWindow)
		self.actionAbout.setEnabled(False)
		self.actionAbout.setObjectName("actionAbout")
		self.actionPreferences = QtWidgets.QAction(MainWindow)
		self.actionPreferences.setEnabled(True)
		self.actionPreferences.setObjectName("actionPreferences")
		self.actionOpen_Profile = QtWidgets.QAction(MainWindow)
		self.actionOpen_Profile.setObjectName("actionOpen_Profile")
		self.actionPrint_PDF = QtWidgets.QAction(MainWindow)
		self.actionPrint_PDF.setObjectName("actionPrint_PDF")
		self.actionExport_HTML = QtWidgets.QAction(MainWindow)
		self.actionExport_HTML.setObjectName("actionExport_HTML")
		self.actionExport_ODF = QtWidgets.QAction(MainWindow)
		self.actionExport_ODF.setObjectName("actionExport_ODF")
		self.actionExport_Plain_Text = QtWidgets.QAction(MainWindow)
		self.actionExport_Plain_Text.setObjectName("actionExport_Plain_Text")
		self.actionExport_docx = QtWidgets.QAction(MainWindow)
		self.actionExport_docx.setObjectName("actionExport_docx")
		self.actionExport_odt = QtWidgets.QAction(MainWindow)
		self.actionExport_odt.setObjectName("actionExport_odt")
		self.actionNew_Profile = QtWidgets.QAction(MainWindow)
		self.actionNew_Profile.setObjectName("actionNew_Profile")
		self.actionSave_Profile_As = QtWidgets.QAction(MainWindow)
		self.actionSave_Profile_As.setObjectName("actionSave_Profile_As")
		self.menuExport_Report.addAction(self.actionPrint_PDF)
		self.menuExport_Report.addAction(self.actionExport_docx)
		self.menuExport_Report.addAction(self.actionExport_odt)
		self.menuExport_Report.addAction(self.actionExport_HTML)
		self.menuExport_Report.addAction(self.actionExport_Plain_Text)
		self.menuFile.addAction(self.actionNew_Profile)
		self.menuFile.addAction(self.actionOpen_Profile)
		self.menuFile.addAction(self.actionSave_Profile)
		self.menuFile.addAction(self.actionSave_Profile_As)
		self.menuFile.addAction(self.menuExport_Report.menuAction())
		self.menuFile.addSeparator()
		self.menuFile.addAction(self.actionQuit)
		self.menuEdit.addAction(self.actionAdd_Section)
		self.menuEdit.addAction(self.actionRemove_Section)
		self.menuEdit.addAction(self.actionMove_Section_Up)
		self.menuEdit.addAction(self.actionMove_Section_Down)
		self.menuTools.addAction(self.actionImport_Package)
		self.menuTools.addAction(self.actionRemove_Package)
		self.menuTools.addSeparator()
		self.menuTools.addAction(self.actionGenerate_Report)
		self.menuTools.addSeparator()
		self.menuTools.addAction(self.actionPreferences)
		self.menuHelp.addAction(self.actionARCTool_Wiki)
		self.menuHelp.addSeparator()
		self.menuHelp.addAction(self.actionAbout)
		self.menuBar.addAction(self.menuFile.menuAction())
		self.menuBar.addAction(self.menuEdit.menuAction())
		self.menuBar.addAction(self.menuTools.menuAction())
		self.menuBar.addAction(self.menuHelp.menuAction())

		self.retranslateUi(MainWindow)
		self.actionGenerate_Report.triggered.connect(self.generateReport.click)
		self.actionQuit.triggered.connect(MainWindow.close)
		self.actionAdd_Section.triggered.connect(self.addSection.click)
		self.actionSave_Profile.triggered.connect(self.saveProfile.click)
		self.actionMove_Section_Up.triggered.connect(self.moveUp.click)
		self.actionMove_Section_Down.triggered.connect(self.moveDown.click)
		self.actionOpen_Profile.triggered.connect(self.openProfile.click)
		self.actionRemove_Section.triggered.connect(self.removeSection.click)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "ARCTool"))
		self.menuFile.setTitle(_translate("MainWindow", "File"))
		self.menuExport_Report.setTitle(_translate("MainWindow", "Export Report"))
		self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
		self.menuTools.setTitle(_translate("MainWindow", "Tools"))
		self.menuHelp.setTitle(_translate("MainWindow", "Help"))
		self.profileLabel.setText(_translate("MainWindow", "Profile:"))
		self.profileName.setPlaceholderText(_translate("MainWindow", "Profile Name"))
		self.label.setText(_translate("MainWindow", "Context:"))
		self.moveUp.setShortcut(_translate("MainWindow", "Ctrl+PgDown"))
		self.moveDown.setShortcut(_translate("MainWindow", "Ctrl+PgUp"))
		self.removeSection.setShortcut(_translate("MainWindow", "Del"))
		self.addSection.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
		self.generateReport.setText(_translate("MainWindow", "Generate Report"))
		self.generateReport.setShortcut(_translate("MainWindow", "Ctrl+G"))
		self.exportReport.setText(_translate("MainWindow", "Export Report..."))
		self.exportReport.setShortcut(_translate("MainWindow", "Ctrl+E"))
		self.sectionTitle.setPlaceholderText(_translate("MainWindow", "Section Title"))
		self.pluginTypeLabel.setText(_translate("MainWindow", "Plugin:"))
		self.pluginButton.setToolTip(_translate("MainWindow", "Click to set Plugin"))
		self.pluginButton.setText(_translate("MainWindow", "Set..."))
		self.showTitle.setText(_translate("MainWindow", "Show Title"))
		self.actionOpen.setText(_translate("MainWindow", "Open..."))
		self.actionSave_Report.setText(_translate("MainWindow", "Save Report..."))
		self.actionSave_Profile.setText(_translate("MainWindow", "Save Profile..."))
		self.actionSave_Profile.setShortcut(_translate("MainWindow", "Ctrl+S"))
		self.action_docx.setText(_translate("MainWindow", ".docx"))
		self.action_PDF.setText(_translate("MainWindow", ".PDF"))
		self.action_odf.setText(_translate("MainWindow", ".odf"))
		self.actionQuit.setText(_translate("MainWindow", "Quit"))
		self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
		self.actionAdd_Section.setText(_translate("MainWindow", "Add Section"))
		self.actionRemove_Section.setText(_translate("MainWindow", "Remove Section"))
		self.actionMove_Section_Up.setText(_translate("MainWindow", "Move Section Up"))
		self.actionMove_Section_Down.setText(_translate("MainWindow", "Move Section Down"))
		self.actionImport_Package.setText(_translate("MainWindow", "Import Package..."))
		self.actionRemove_Package.setText(_translate("MainWindow", "Remove Package..."))
		self.actionGenerate_Report.setText(_translate("MainWindow", "Generate Report"))
		self.actionARCTool_Wiki.setText(_translate("MainWindow", "ARCTool Wiki"))
		self.actionAbout.setText(_translate("MainWindow", "About"))
		self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
		self.actionOpen_Profile.setText(_translate("MainWindow", "Open Profile..."))
		self.actionOpen_Profile.setShortcut(_translate("MainWindow", "Ctrl+O"))
		self.actionPrint_PDF.setText(_translate("MainWindow", "Print PDF..."))
		self.actionExport_HTML.setText(_translate("MainWindow", "Export HTML..."))
		self.actionExport_ODF.setText(_translate("MainWindow", "Export odf..."))
		self.actionExport_Plain_Text.setText(_translate("MainWindow", "Export Plain Text..."))
		self.actionExport_docx.setText(_translate("MainWindow", "Export docx..."))
		self.actionExport_odt.setText(_translate("MainWindow", "Export odt..."))
		self.actionNew_Profile.setText(_translate("MainWindow", "New Profile"))
		self.actionNew_Profile.setShortcut(_translate("MainWindow", "Ctrl+N"))
		self.actionSave_Profile_As.setText(_translate("MainWindow", "Save Profile As..."))
		self.actionSave_Profile_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))

