# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pluginselectdialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PluginSelectDialog(object):
	def setupUi(self, PluginSelectDialog):
		PluginSelectDialog.setObjectName("PluginSelectDialog")
		PluginSelectDialog.resize(507, 228)
		self.verticalLayout = QtWidgets.QVBoxLayout(PluginSelectDialog)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.packageList = QtWidgets.QListWidget(PluginSelectDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.packageList.sizePolicy().hasHeightForWidth())
		self.packageList.setSizePolicy(sizePolicy)
		self.packageList.setObjectName("packageList")
		self.horizontalLayout.addWidget(self.packageList)
		self.pluginList = QtWidgets.QListWidget(PluginSelectDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pluginList.sizePolicy().hasHeightForWidth())
		self.pluginList.setSizePolicy(sizePolicy)
		self.pluginList.setObjectName("pluginList")
		self.horizontalLayout.addWidget(self.pluginList)
		self.widget = QtWidgets.QWidget(PluginSelectDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
		self.widget.setSizePolicy(sizePolicy)
		self.widget.setObjectName("widget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.name = QtWidgets.QLabel(self.widget)
		font = QtGui.QFont()
		font.setPointSize(16)
		font.setBold(True)
		font.setWeight(75)
		self.name.setFont(font)
		self.name.setAlignment(QtCore.Qt.AlignCenter)
		self.name.setObjectName("name")
		self.verticalLayout_2.addWidget(self.name)
		self.author = QtWidgets.QLabel(self.widget)
		self.author.setAlignment(QtCore.Qt.AlignCenter)
		self.author.setWordWrap(True)
		self.author.setObjectName("author")
		self.verticalLayout_2.addWidget(self.author)
		self.version = QtWidgets.QLabel(self.widget)
		self.version.setAlignment(QtCore.Qt.AlignCenter)
		self.version.setObjectName("version")
		self.verticalLayout_2.addWidget(self.version)
		spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
		self.verticalLayout_2.addItem(spacerItem)
		self.description = QtWidgets.QLabel(self.widget)
		self.description.setTextFormat(QtCore.Qt.RichText)
		self.description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
		self.description.setWordWrap(True)
		self.description.setIndent(6)
		self.description.setOpenExternalLinks(True)
		self.description.setObjectName("description")
		self.verticalLayout_2.addWidget(self.description)
		spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
		self.verticalLayout_2.addItem(spacerItem1)
		self.horizontalLayout.addWidget(self.widget)
		self.horizontalLayout.setStretch(0, 1)
		self.horizontalLayout.setStretch(1, 1)
		self.horizontalLayout.setStretch(2, 2)
		self.verticalLayout.addLayout(self.horizontalLayout)
		self.buttonBox = QtWidgets.QDialogButtonBox(PluginSelectDialog)
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
		self.buttonBox.setObjectName("buttonBox")
		self.verticalLayout.addWidget(self.buttonBox)
		self.verticalLayout.setStretch(0, 1)

		self.retranslateUi(PluginSelectDialog)
		self.buttonBox.accepted.connect(PluginSelectDialog.accept)
		self.buttonBox.rejected.connect(PluginSelectDialog.reject)
		QtCore.QMetaObject.connectSlotsByName(PluginSelectDialog)

	def retranslateUi(self, PluginSelectDialog):
		_translate = QtCore.QCoreApplication.translate
		PluginSelectDialog.setWindowTitle(_translate("PluginSelectDialog", "Dialog"))
		self.packageList.setSortingEnabled(True)
		self.pluginList.setSortingEnabled(True)
		self.name.setText(_translate("PluginSelectDialog", "Plugin Name"))
		self.author.setText(_translate("PluginSelectDialog", "Author"))
		self.version.setText(_translate("PluginSelectDialog", "Version"))
		self.description.setText(_translate("PluginSelectDialog", "Description"))

